## NUMPY array and basics

In [2]:
import numpy as np

In [3]:
arr_1d = np.array([1,2,3,4,5])
print("1D array: ",arr_1d)


arr_2d =np.array([[1,2,3],[4,5,6]])
print("2D array: ",arr_2d)

1D array:  [1 2 3 4 5]
2D array:  [[1 2 3]
 [4 5 6]]


### List Vs Numpy array

In [ ]:
py_list = [1,2,3]
print("Python list multiplication",py_list*2)

np_array = np.array([1,2,3]) #element wise multipliction
print("Python array multiplication",np_array*2)


import time
start = time.time() #starting time 
py_list=[i*2 for i in range(10000000)] #list comprehension
print("\n list operation time: ",time.time()-start) #elapsed time 


start = time.time()
np_array=np.arange(10000000)*2  #it creates a numpy array of integers from 0 to 9999999
print("\n Numpy operation time: ",time.time()-start)



Python list multiplication [1, 2, 3, 1, 2, 3]
Python array multiplication [2 4 6]

 list operation time:  1.0042424201965332

 Numpy operation time:  0.06734108924865723


### Creating array from scratch


In [10]:
zeros = np.zeros((3,4))
print("zeros array: \n",zeros)

ones = np.ones((3,4))
print("ones array: \n",ones)


full = np.full((2,2),7)
print("full array: \n",full)

random = np.random.random((2,3))
print("random array: \n",random)


sequence = np.arange(0,10,2) # non inclusive outer boundary
print("sequence array: \n",sequence)


zeros array: 
 [[0. 0. 0. 0.]
 [0. 0. 0. 0.]
 [0. 0. 0. 0.]]
ones array: 
 [[1. 1. 1. 1.]
 [1. 1. 1. 1.]
 [1. 1. 1. 1.]]
full array: 
 [[7 7]
 [7 7]]
random array: 
 [[0.31532458 0.1105262  0.48233687]
 [0.38719107 0.61318543 0.92966799]]
sequence array: 
 [0 2 4 6 8]


### Vector, Matrix and Tensor

In [ ]:
#A vector is a 1d array
vector = np.array([1,2,3])
print("Vector: ",vector)

#A Matrices is a (2D array)
matrix = np.array([[1,2,3],[4,5,6]])
print("Matrix: ",matrix)

#A tensor is just a multi-dimensional array.
tensor = np.array([[[1,2],[3,4]],
                   [[5,6],[7,8]]])
print("Tensor: ",tensor)

Vector:  [1 2 3]
Matrix:  [[1 2 3]
 [4 5 6]]
Tensor:  [[[1 2]
  [3 4]]

 [[5 6]
  [7 8]]]


### Array Properties


In [ ]:
array = np.array([[1,2,3],
                [4,5,6]])
print("Shape: ",array.shape) #it gives rows and columns
print("Dimensions: ",array.ndim) #1d array = dim = 1 , 2d array = dim = 2.
print("Size: ",array.size) #total number of elements in the array. 2 rows 3 column = 2*3=6
print("DType: ",array.dtype)#Shows the data type of the array's elements.

Shape:  (2, 3)
Dimensions:  2
Size:  6
DType:  int64


### Array Reshaping


In [ ]:
arr=np.arange(12)
print("Original Array: ",arr)

reshaped = arr.reshape((3,4))
print("\n Reshaped Array: ",reshaped)

# it returns a copy of the original array
flattended = reshaped.flatten()
print("\n Flattened Array: ",flattended)


# (returns view , instead of copy)
#if you change the view, the original array is also changed, because both are sharing the same memory.
raveled = reshaped.ravel()
print("\n Raveled Array: ",raveled)


#Transpose
#flipping a matrix rows into columns and vice versa
transpose = reshaped.T  
print("\n Transpose Array: ",transpose)






Original Array:  [ 0  1  2  3  4  5  6  7  8  9 10 11]

 Reshaped Array:  [[ 0  1  2  3]
 [ 4  5  6  7]
 [ 8  9 10 11]]

 Flattened Array:  [ 0  1  2  3  4  5  6  7  8  9 10 11]

 Raveled Array:  [ 0  1  2  3  4  5  6  7  8  9 10 11]

 Transpose Array:  [[ 0  4  8]
 [ 1  5  9]
 [ 2  6 10]
 [ 3  7 11]]
