## Numpy Array operations 

In [1]:
import numpy as np

In [5]:
arr = np.array([1,2,3,4,5,6,7,8,9,10])
print("Basic Slicing: ",arr[2:7])
print("With Steps: ",arr[1:9:2])
print("Negative Sicing: ",arr[-3])

Basic Slicing:  [3 4 5 6 7]
With Steps:  [2 4 6 8]
Negative Sicing:  8


In [ ]:
arr_2d = np.array([[1,2,3],    #this is 0th row
                   [4,5,6],    #this is 1st row
                   [7,8,9]])
print("Specific Element: ",arr_2d[1,2])  # here [which row , element in that specific row]
print("Entire Row: ",arr_2d[1])  # it gives entire row
print("Entire Column: ",arr_2d[:,1]) # it gives entire column 

Specific Element:  6
Entire Row:  [4 5 6]
Entire Column:  [2 5 8]


## Sorting

In [ ]:
unsorted = np.array([3,1,4,1,5,9,2,6])
print("Original array: ", unsorted)
print("Sorted array: ",np.sort(unsorted))


# another way 
arr_2d_unsorted = np.array([[3,1],
                            [1,2],
                            [2,3]])
print("Sorted 2D array by column: ",np.sort(arr_2d_unsorted, axis=0))  # top to bottom sorting 
print("Sorted 2D array by row: ",np.sort(arr_2d_unsorted, axis=1)) # left to right sorting

Original array:  [3 1 4 1 5 9 2 6]
Sorted array:  [1 1 2 3 4 5 6 9]
Sorted 2D array by column:  [[1 1]
 [2 2]
 [3 3]]
Sorted 2D array by row:  [[1 3]
 [1 2]
 [2 3]]


## Filtering

In [ ]:
numbers = np.array([1,2,3,4,5,6,7,8,9,10])
even_number = numbers[numbers % 2==0]
print("Even Numbers: ",even_number)

Even Numbers:  [ 2  4  6  8 10]


## Filter with mask

In [12]:
mask = numbers > 5
print("Numbers greater than 5: ",numbers[mask])  

Numbers greater than 5:  [ 6  7  8  9 10]


## Fancy indexing vs np.where()

In [14]:
indices = [0,2,4]
print(numbers[indices])


where_result =np.where(numbers > 5)
print("Np where: ",numbers[where_result])

[1 3 5]
Np where:  [ 6  7  8  9 10]


In [20]:
condition_array0 = np.where(numbers > 5, numbers , numbers)
condition_array1 = np.where(numbers > 5, numbers * 1, numbers)
condition_array2 = np.where(numbers > 5, numbers * 2, numbers)
condition_array3 = np.where(numbers > 5, numbers * 4, numbers)
condition_array4 = np.where(numbers > 5, "true", "false")
print(condition_array0)
print(condition_array1)
print(condition_array2)
print(condition_array3)
print(condition_array4)


# this is same like an if and else case
#if(numbers > 5){
#  numbers * 4  
#}else{
#   numbers 
#}

[ 1  2  3  4  5  6  7  8  9 10]
[ 1  2  3  4  5  6  7  8  9 10]
[ 1  2  3  4  5 12 14 16 18 20]
[ 1  2  3  4  5 24 28 32 36 40]
['false' 'false' 'false' 'false' 'false' 'true' 'true' 'true' 'true'
 'true']


## Adding and Removing data

In [21]:
arr1 =np.array([1,2,3])
arr2 =np.array([4,5,6])

combined = arr1+arr2  # its just add the entire array column wise 
print(combined)  # output: [5 7 9]

combined_array = np.concatenate((arr1,arr2))
print(combined_array)

[5 7 9]
[1 2 3 4 5 6]


## Array compatibility

In [23]:
a = np.array([1,2,3])
b = np.array([4,5,6])
c = np.array([7,8,9])
d= np.array([10,11,12,13])
print("Compatibility Shapes: ",a.shape == b.shape)
print("Compatibility Shapes: ",a.shape == d.shape)

Compatibility Shapes:  True
Compatibility Shapes:  False


In [27]:
original = np.array([[1,2],
                     [3,4]])
new_row = np.array([[5,6]])

with_new_row = np.vstack((original, new_row))
print("Original: ",original)
print("With new row: ",with_new_row)

new_col = np.array([[7],
                   [8]])
with_new_col = np.hstack((original , new_col))
print("With new Col: ",with_new_col)

Original:  [[1 2]
 [3 4]]
With new row:  [[1 2]
 [3 4]
 [5 6]]
With new Col:  [[1 2 7]
 [3 4 8]]


## Delete

In [29]:
arr = np.array([1,2,3,4,5])
deleted = np.delete(arr,2)
print("Array after deletion: ",deleted)

Array after deletion:  [1 2 4 5]
