In [2]:
import numpy as np

In [8]:
arr = np.array([1,2,3,4])
print(arr)

arr_2d = np.array([[1,2,3],
                   [4,5,6]])
print(arr_2d)

arr_tensor = np.array([
    [[1,2,3]],
    [[7,8,9]],
    [[3,1,5]]
])
print(arr_tensor)

[1 2 3 4]
[[1 2 3]
 [4 5 6]]
[[[1 2 3]]

 [[7 8 9]]

 [[3 1 5]]]


In [9]:
list = [1,2,3]
print(list * 2)

[1, 2, 3, 1, 2, 3]


In [11]:
print(arr_2d.shape)

(2, 3)
